### PR TITLE
Include license to generated HTML

### PR DESCRIPTION
**Pull request by kianmeng**
Include the license file to the final generated HTML doc for HexDocs.pm.

### CODE REVIEW

**Comment by swelham** [comment]
Hey, thanks for the PR.

There seems to be many different changes going here that aren't necessarily related to one another. This makes it tricky to review and understand the motivation behind each change. If possible would you be able to break this out into multiple PRs that each focus on one type of change? For example, a PR for ex_doc upgrade/changes, another for code formatting changes, etc...

**Comment by kianmeng** [comment]
> Hey, thanks for the PR.
> 
> There seems to be many different changes going here that aren't necessarily related to one another. This makes it tricky to review and understand the motivation behind each change. If possible would you be able to break this out into multiple PRs that each focus on one type of change? For example, a PR for ex_doc upgrade/changes, another for code formatting changes, etc...

@swelham Sure. :smile: 
Let's start with this one then, https://github.com/swelham/ueberauth_microsoft/pull/24/files

**Comment by kianmeng** [comment]
@swelham Please check again!

**Comment by swelham** [comment]
Thanks 👍

**Pull request merged**
